Sunder-System/Sunder

- Sunder.xml
removed tainhelm target list
updated fish.msg to snd.fishmsg
gmcp chat rewrite
> more backlogged changes

- Sunder.xml
Now prioritizes hitting aggressive mobs.
> Aggressive mob support for bashy stuff

- Sunder.xml
Just catching up with requested changes / bug fixes to the system
> Misc pending changes

- Sunder.xml
improved Akkari tracking, bugfixes, added 2 new routes. Thank you to Xavin and Rhesk for their help.
> Akkari update!

- Sunder.xml
-Mystified tracking trigger fix to capture correctly (RC). 
-Additional tracking trigger for RC darkness affs. 
-Fixing of epidermal head curing to allow for sight to be on target if they use epidermal without any of the prior affs in place. 
-Addition of Xavin's selfishness info.
-Fix of panacea curing, though it needs more work still around if the room doesn't have darkness. 
-Removed some requirements around true about darkness in room that weren't needed. 
-Fixed the duplication of 'Infect' in the all attacks table to be Inoculation.
> Zortania Suggested Fixes

- Sunder.xml
-Added trigger lines for when reflections are lost, just in case def_reflection isn't properly tracking. 
-Same with additional Branch triggers.
-Added an 'already has rot' trigger in case curing inaccurately tracks rot. 
-Added in snd.repay system, for tracking if you should repay or not in Scio/RC. 
-Updated Sciomancer aliases, since they were not accurately setup to mirror what I gave for RC. 
-Fixed RC bashing to make sure it checks you  have a reflection first. 
-Fixed two def removals that were incorrectly setup. 
-Removed 'stuttering' as a mental aff, as it's not. 
-Built out tables for anxieties and 'other' affs (which is mostly random affs). 
-Built out an aff counter for 'real_all_affs', which will include all those 'other' affs for a true affliction counter. 
-Added in …
> Zortania Updates v2

- Sunder.xml
Triggers added:
"asleep" - gives asleep aff
"no asleep" - cures asleep aff
"stood" - updated to cure asleep
"voyria cured" - updated to cure voyria
"numbed_skin" - updated to cure Assassination Marks (Numbed Skin)
snd.effects:
Added asleep = "delphinium" to table
> Teflin's Tracking fixes

- Sunder.xml
I forgot snd.repay needed to be fixed. Thanks Xavin!
> Runecarver Alias Fix

- Sunder.xml
Let's just say bashing is made to make you more tanky, be newbie-friendly, and just flow better.
> So many updates

- Sunder.xml
-Replaced all instances of aegis to dome.
-Input a few bugs for Templar/Revenant on tracking cripple. 
-Updated on Tidesage alias with a hammering option. 
-Updated Ravager aliases to replace rampage with overpower. 
-Updated limb restoration stuff based on what was given in Discord.
> Zortania Updates

- Sunder.xml
Quick fix on the restoration tracking update in tracking functions. Thanks Lerad.
> Restoration Re-Fix

- Sunder.xml
Just adding a variable used in some of my aliases around deform/disjunct.
> Deform/Disjunct Tracking

- Sunder.xml
-Added reset of fulcrum on death.
-Added another line for if there is no target in your room. 
-Fixed tracking on elemental squeeze (tidesage).
-Fixed tracking on synthesis squeeze.
-Did adjustments to basher to make it not  spam 'none' and hopefully give some echoes if something isn't working right. Thanks Vaessa for working with me on this! 
-Fixed Ascendril/Bloodborn bashing so it should try to call fulcrum/well if you have no resonance or fulcrum. 
-Added Wavebreaking Crack tracking.
-Fixed an issue with Unundation Feelers tracking for storm and not apparition in all attacks. 
-Added Trammel and Deconstruct tracking for Synthesis.
> Small Fixes

- Sunder.xml
-Put in a need to fulcrum call after you die. Need someone to confirm if death destroys it. 
-Added in a flag for fulcrum existing. Should flag appropriately. Might need more lines for it and calling. 
-Updated Ascendril/Bloodborn bash to make fulcrum/well if it doesn't know if it exists. Technically, if we have the right triggers, it should flag that away if it does exist for some reason. Then, it'll call if it thinks it needs to call. If it doesn't need to do those two things, move on.
> ASCENDRIL OMG

- Sunder.xml
There are a number of places where 'deafness' is listed when it should be 'hearing'.
> Deafness versus hearing

- Sunder.xml
From her file provided in Discord.
> Vaessa Updates

- Sunder.xml
-added treant to shadow vortex bashing target list
-fixed praenomen stalk and shadowblow
-closed the regex for bloodborne fire route
-a target using focus will now remove the impatience aff from them.
-fixed syntax of praenomen purify
-fixed sciomancer's single attack script referencing spiritpact instead of shadowprice
> Misc fixes

- Sunder.xml
class_bash_override function functionality added
More alchemist defence support.
added lines for berserking to shield and rebounding raze triggers
put sgs samples, commented out, in the global item table.
> Assorted changes.

- Sunder.xml
Fixed isle of ollin start room.
> added default entry for empowered moon.

- Sunder.xml
Fixed issue w/ discern and crippled/crippled body (it was processing them like they were a crippled limb)
> Implemented more of akkari tracking changes for praenomen.

- Sunder.xml
terramancy absorb trigger line added.
Panacea check rewritten
needle aff tracking fix
besilience check for rage
wayfarer route fixes
> Assorted fixes.

- Sunder.xml
> Catch up main repo
